#!/usr/bin/env python3
"""Generate Python casefold exceptions for the Worker, using the pinned Python runtime."""
import argparse
import json
from pathlib import Path
import sys
import unicodedata

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "shared/credit-normalization.ts"


def generated_source() -> str:
    folds = {chr(code): chr(code).casefold() for code in range(sys.maxunicode + 1)
             if chr(code).casefold() != chr(code).lower()}
    whitespace = ''.join(f'\\u{code:04x}' for code in range(sys.maxunicode + 1) if chr(code).isspace())
    return (f'// Generated by tools/generate_credit_normalization.py; Unicode {unicodedata.unidata_version}.\n'
            '// Python NFKC + casefold + strip is the stored composer-index contract.\n'
            'const CASE_FOLDS: Record<string, string> = ' + json.dumps(folds, ensure_ascii=True, separators=(',', ':')) + ';\n\n'
            'export function normalizeCreditName(value: string): string {\n'
            '  const folded = Array.from(value.normalize("NFKC"), character => CASE_FOLDS[character] ?? character.toLowerCase()).join("");\n'
            f'  return folded.replace(/^[{whitespace}]+|[{whitespace}]+$/gu, "");\n'
            '}\n')


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    source = generated_source()
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text() != source:
            print('Composer normalization table is stale; run tools/generate_credit_normalization.py', file=sys.stderr)
            return 1
        print('Composer normalization table matches Python.')
    else:
        OUTPUT.write_text(source)
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
